name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_firmware:
    env:
      target: firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'

    - name: Build firmware
      run: |
        git submodule update --init --recursive
        make libopencm3
        make -j

    - name: Upload firmware binaries
      uses: actions/upload-artifact@v2-preview
      with:
        name: firmware_binary
        path: ./*.elf
